# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: RemUI Automation
run-name: RemUI Automation Testing

on:
  push:
    branches: [ "release" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file EdwiserRemui/pom.xml
      
    - name: Upload Surefire reports
      id: upload
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Testing-Report
        path: EdwiserRemui/target/surefire-reports/emailable-report.html


# Send the email with the Surefire report
    - name: Send Surefire Report via Email
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "RemUI Maven Surefire Test Report"
          body: "Attached is the Surefire test report from the latest build."
          to: 'ymdeore93@gmail.com'
          from: ${{ secrets.SMTP_USERNAME }}
          attachments: EdwiserRemui/target/surefire-reports/emailable-report.html
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
