name: Send report
on:
  workflow_run:
    workflows: [Java CI with Maven]
    types: [completed]

jobs:
  pin-artifacts:
    permissions:
      statuses: write
    name: Add artifacts links to commit statuses
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send artifacts links
        id: set_var
        run: |
          set -x
          workflow_id=${{ github.event.workflow_run.workflow_id }}
          run_id=${{ github.event.workflow_run.id }}  # instead of ${{ github.run_id }}
          run_number=${{ github.event.workflow_run.run_number }}
          head_branch=${{ github.event.workflow_run.head_branch }}
          head_sha=${{ github.event.workflow_run.head_sha }}  # instead of ${{ github.event.pull_request.head.sha }} (or ${{ github.sha }})
          check_suite_id=${{ github.event.workflow_run.check_suite_id }}
          set +x

          curl \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/artifacts" \
          | jq '[.artifacts | .[] | .id]' \
          > artifacts.txt

          content=`cat artifacts.txt`
          echo "::set-output name=id::$content"
          
      - name: Send email with Surefire report
        if: ${{ always() }}
        uses: mmichailidis/sendgrid-mail-action@v1.0
        with:
          sendgrid-token: ${{ secrets.SENDGRID_API_KEY }}
          mail: 'yogesh.deore@wisdmlabs.com,abhay.vishwakarma@wisdmlabs.com'
          from: 'yogesh.deore@wisdmlabs.com'
          subject: Build failure - Surefire report
          text: "https://github.com/${{ github.repository }}/suites/${{ github.event.workflow_run.check_suite_id }}/artifacts/${{ steps.set_var.outputs.id }} The build has been failed. Please find the Surefire report attached."
          individual: true
          splitterator: ','
