name: Send report
on:
  workflow_run:
    workflows: [Java CI with Maven]
    types: [completed]

jobs:
  pin-artifacts:
    permissions:
      statuses: write
    name: Sending report link in Email
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Getting artifact link
        id: set_var
        run: |
          set -x
          workflow_id=${{ github.event.workflow_run.workflow_id }}
          run_id=${{ github.event.workflow_run.id }}  # instead of ${{ github.run_id }}
          run_number=${{ github.event.workflow_run.run_number }}
          head_branch=${{ github.event.workflow_run.head_branch }}
          head_sha=${{ github.event.workflow_run.head_sha }}  # instead of ${{ github.event.pull_request.head.sha }} (or ${{ github.sha }})
          check_suite_id=${{ github.event.workflow_run.check_suite_id }}
          set +x

          curl \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/artifacts" \
          | jq '[.artifacts|.[]|["id":.id]]' \
          > artifacts.json
          content=`cat artifacts.json`
          # the following lines are only required for multi line json
          content="${content//$'{\n'/''}"
          content="${content//$'}\n'/''}"
          content="${content//$'{\r'/''}"
          content="${content//$'}\r'/''}"
          content="${content//'%'/''}"
          content="${content//$'\n'/''}"
          content="${content//$'\r'/''}"
          content="${content//$'['/''}"
          content="${content//$']'/''}"
          content="${content//$' '/''}"
          content="${content//$'"'/''}"
          content="${content//$'id'/''}"
          content="${content//$':'/''}"
          content="${content//$'{'/''}"
          content="${content//$'}'/''}"
          # end of optional handling for multi line json
          
          echo "packageJson={$content}" >> $GITHUB_OUTPUT
      - run: |
          temp_content=${{ steps.set_var.outputs.packageJson }}
          temp_content="${temp_content//$'{'/''}"
          temp_content="${temp_content//$'}'/''}"
          echo "packageJson={$temp_content}" >> $GITHUB_OUTPUT

      - name: Send email with Surefire report
        if: ${{ always() }}
        uses: mmichailidis/sendgrid-mail-action@v1.0
        with:
          sendgrid-token: ${{ secrets.SENDGRID_API_KEY }}
          mail: 'yogesh.deore@wisdmlabs.com,abhay.vishwakarma@wisdmlabs.com'
          from: 'yogesh.deore@wisdmlabs.com'
          subject: Surefire report
          text: "https://github.com/${{ github.repository }}/suites/${{ github.event.workflow_run.check_suite_id }}/artifacts/${{ steps.set_var.outputs.packageJson }} The build has been failed. Please find the Surefire report attached."
          individual: true
          splitterator: ','
