name: Send Email via SMTP

on:
  workflow_run:
    workflows: [RemUI Automation]
    types: [completed]
    branches: [release]
jobs:
  pin-artifacts:
    permissions:
      statuses: write
    name: Sending report link in Email
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest

    steps:
      - name: Getting artifact link
        id: set_var
        run: |
          set -x
          # Set workflow and run details from the event payload
          workflow_id=${{ github.event.workflow_run.workflow_id }}
          run_id=${{ github.event.workflow_run.id }}
          run_number=${{ github.event.workflow_run.run_number }}
          head_branch=${{ github.event.workflow_run.head_branch }}
          head_sha=${{ github.event.workflow_run.head_sha }}
          check_suite_id=${{ github.event.workflow_run.check_suite_id }}
          set +x

          # Get the artifacts for the specified run_id
          response=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.Auth_Bearer }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ run_id }}/artifacts")

          # Parse the artifact IDs using jq
          artifact_ids=$(echo "$response" | jq -r '.artifacts[].id')

          # Check if artifacts were found and set the artifact ID
          if [ -z "$artifact_ids" ]; then
            echo "No artifacts found for this run."
            exit 1
          fi

          echo "Artifacts IDs: $artifact_ids"

          # Optionally: Save the artifact IDs to a file or use in later steps
          echo "ARTIFACT_IDS=$artifact_ids" >> $GITHUB_ENV

          # Print the JSON response (for debugging)
          echo "Full response: $response"


      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "GitHub Action Notification"
          body: "Some testcases from automation testing are failed. You can find the detailed report here : https://github.com/${{ github.repository }}/suites/${{ github.event.workflow_run.check_suite_id }}/artifacts/${{ steps.set_var.outputs.packageJson }} ."
          to: 'ymdeore93@gmail.com'
          from: ${{ secrets.SMTP_USERNAME }}
          secure: true  # Set to false for non-encrypted connections
